package com.example.filelistview.data;
import jakarta.persistence.*;

/**
 * We want to store request history.
 * This class is where define which data will be store in the DB
 */
@Entity
@Table(name = "history")
public class History {

    /**
     * A Unique ID, We don't give this, it will be autogenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Which server handle the request
     */
    private String Who;

    /**
     * How many good files needed
     */
    private Integer FileNum;

    /**
     * How many mistaken files needed
     */
    private Integer MistakeNum;

    /**
     * When requested it.
     */
    private long RequestTime;

    /**
     * What was the result of the List Tree View
     */
    @Column(columnDefinition = "text")
    private String Result;


    /**
     * Getter For Who
     * @return The value of Who
     */
    public String getWho() {
        return Who;
    }

    /**
     * Setter For Who
     * @param who is the new value of Who
     */
    public void setWho(String who) {
        Who = who;
    }

    /**
     * Getter For getRequestTime
     * @return The value of getRequestTime
     */
    public long getRequestTime() {
        return RequestTime;
    }

    /**
     * Setter For RequestTime
     * @param RequestTime is the new value of RequestTime
     */
    public void setRequestTime(long RequestTime) {
        this.RequestTime = RequestTime;
    }

    /**
     * Getter For Result
     * @return The value of Result
     */
    public String getResult() {
        return Result;
    }

    /**
     * Setter For result
     * @param result is the new value of result
     */
    public void setResult(String result) {
        Result = result;
    }

    /**
     * Getter For FileNum
     * @return The value of FileNum
     */
    public Integer getFileNum() {
        return FileNum;
    }

    /**
     * Setter For fileNum
     * @param fileNum is the new value of fileNum
     */
    public void setFileNum(Integer fileNum) {
        FileNum = fileNum;
    }

    /**
     * Getter For MistakeNum
     * @return The value of MistakeNum
     */
    public Integer getMistakeNum() {
        return MistakeNum;
    }

    /**
     * Setter For mistakeNum
     * @param mistakeNum is the new value of mistakeNum
     */
    public void setMistakeNum(Integer mistakeNum) {
        MistakeNum = mistakeNum;
    }

    /**
     * Getter For id
     * @return The value of id
     */
    public Long getId() {
        return id;
    }

    /**
     * Setter For id
     * @param id is the new value of id
     */
    public void setId(Long id) {
        this.id = id;
    }
}
